# -*- coding: utf-8 -*-
"""ComoCrearFunciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iz61s8cz-Y-u6Q4fF05oLGI4LXZjcAZL

Funciones
"""

def nombre_funcion(argumento):
  codigo
  return retorno

"""Función multiplo"""

#Para crear una función primero defino las condiciones de la función
def es_multiplo(numero):
  if numero % 3 == 0:
    return True
  else:
    return False

#ahora utilizo la función. Esta parte es llamada función principal
num = int(input("Ingresa un numero: ")) #ingreso una variable que contenga int para recibir un numero desde el usuario


if es_multiplo(num): #Hago llamado a la función y a la variable
  print("Es múltipo de 3")
else:
  print("No es múltiplo de 3")

"""Funciona raíz cuadrada"""

def raiz_cuadrada(numero):
  if numero < 0 :
    return "Error: el número es negativo"
  else:
    return numero ** 0.5
num = float(input("Ingresa un número para calcular su raíz cuadrada"))
resultado = raiz_cuadrada(num)
print("resultado", resultado)

"""Área de un rectangulo"""

def area_rectangulo(base, altura):
  if base < 0 or altura < 0:
    return"Error: La base y altura no pueden ser negativas."
  else:
    return base * altura
try:
  base = float(input("Ingresa la base del rectángulo:"))
  altura = float(input("ingresa la altura del rectángulo:"))

  resultado = area_rectangulo(base, altura)
  print("Resultado:", resultado)
except ValuError:
  print("Error: Debes ingresar valores numéricos válidos.")

#funcion promedio
def promedio(n1, n2, n3):
  return (n1 + n2 +n3) / 3

try:
  nota1 = float(input("ingresa nota nº1"))
  nota2 = float(input("ingresa nota nº2"))
  nota3 = float(input("ingresa nota nº3"))

#se debe evitar errores
  if 1.0 <= nota1 <= 7.0 and 1.0 <= nota2 <= 7 and 1.0 <= nota3 <= 7:
    print("Tu promedio es", promedio)
  else:
    print("Error")
except ValueError:
  print("Error: Debes ingresar valores numéricos válidos.")

import math #traer toda la libreria/modulo math

from math import sqrt,log #para importar sólo lo que utilizaré

# funciones especificas de math
math.sqrt(x) # calcula la raíz cuadrada de x.
math.pow(x, y) # calcula x elevado a la potencia y.
# Trigonometría:
math.sin(x) # seno
math.cos(x) # coseno
math.tan(x) # tangente de un ángulo en radianes.
math.degrees(x) # grados
math.radians(x) # radianes.
# Logaritmos:
math.log(x, [base]) # Devuelve el logaritmo de x en una base dada (logaritmo natural si no se especifica la base).
math.log10(x)# Calcula el logaritmo en base 10.
math.log2(x)# Calcula el logaritmo en base 2.
# Redondeo y parte entera:
math.ceil(x) # Devuelve el entero más pequeño mayor o igual que x.
math.floor(x) # Devuelve el entero más grande menor o igual que x.
# Otras funciones:
math.factorial(n) # Calcula el factorial de n.
math.gcd(a, b) # Encuentra el máximo común divisor de dos números.
math.exp(x) # Devuelve e elevado a la potencia x.

