# -*- coding: utf-8 -*-
"""Ejercicios-If-Else.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeuzAub7IMZX4Us57iTzgtvICNutcKsY
"""

#Ejercicio 1. Semáforo
 semaforo = input("Color del semáforo (rojo, amarillo, verde): ").lower() #No hay conversión, porque el color del semáforo ingresa es una cadena
 if semaforo == "verde":
    print("Cruzar la calle" )
 else:
    print("Esperar")

#Ejercicio 2. Verificar mayoría de edad
edad = int(input("¿Cuántos años tienes? "))

if edad >= 18:
    print("Eres mayor de edad.")
else:
    print("Eres menor de edad.")

#Ejercicio 3. Número Positivo
numero = float(input("Ingresa un número: "))

if numero > 0:
    print("El número es positivo.")
else:
    print("El número no es positivo.")

#Ejercicio 4. Verificar si un número es par
numero = int(input("Ingresa un número: "))

if numero % 2 == 0:
    print("El número es par.")
else:
    print("El número es impar.")

#Ejercicio 5. Verificar si una palabra contiene la letra "a"
palabra = input("Escribe una palabra: ")

if "a" in palabra:
    print("La palabra contiene la letra 'a'.")
else:
    print("La palabra no contiene la letra 'a'.")

#Ejercicio 6. Importe
totalcompra = float(input("Ingresa el total de la compra: "))

if totalcompra > 100:
    tasadescuento = 10  # porcentaje
    importedescuento = totalcompra * tasadescuento / 100
    importeapagar = totalcompra - importedescuento
    print("Se aplica un descuento del 10%.")
    print("El importe a pagar es:", importeapagar)
else:
    importeapagar = totalcompra
    print("No aplica descuento.")
    print("El importe a pagar es:", importeapagar)